-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT '6eb87520740ed4b2' HASH '0faa952962c7b6ba5428021e3b17bc13817458779fb055af3d61b9acddb43fd8' ADMIN;         
CREATE SEQUENCE "PUBLIC"."CUSTOMER_ORDER_SEQ" START WITH 1 INCREMENT BY 50;   
CREATE SEQUENCE "PUBLIC"."KITCHEN_CATEGORY_SEQ" START WITH 1 INCREMENT BY 50; 
CREATE SEQUENCE "PUBLIC"."KITCHEN_STOCK_SEQ" START WITH 1 INCREMENT BY 50;    
CREATE SEQUENCE "PUBLIC"."MEAL_TIME_SEQ" START WITH 1 INCREMENT BY 50;        
CREATE SEQUENCE "PUBLIC"."MENU_CATEGORY_SEQ" START WITH 1 INCREMENT BY 50;    
CREATE SEQUENCE "PUBLIC"."MENU_ITEM_SEQ" START WITH 1 INCREMENT BY 50;        
CREATE SEQUENCE "PUBLIC"."MENU_ITEM_STOCK_SEQ" START WITH 1 INCREMENT BY 50;  
CREATE SEQUENCE "PUBLIC"."ORDER_ITEM_SEQ" START WITH 1 INCREMENT BY 50;       
CREATE SEQUENCE "PUBLIC"."RESERVATION_SEQ" START WITH 1 INCREMENT BY 50;      
CREATE SEQUENCE "PUBLIC"."ROLES_SEQ" START WITH 1 INCREMENT BY 50;            
CREATE SEQUENCE "PUBLIC"."SUB_CATEGORY_SEQ" START WITH 1 INCREMENT BY 50;     
CREATE SEQUENCE "PUBLIC"."USERS_SEQ" START WITH 1 INCREMENT BY 50;            
CREATE SEQUENCE "PUBLIC"."USER_ROLE_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;       
CREATE CACHED TABLE "PUBLIC"."CUSTOMER_ORDER"(
    "TOTAL_PRICE" FLOAT(53) NOT NULL,
    "ORDER_ID" BIGINT NOT NULL,
    "RESERVATION_ID" BIGINT NOT NULL,
    "STATUS" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."CUSTOMER_ORDER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ORDER_ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER_ORDER;          
CREATE CACHED TABLE "PUBLIC"."KITCHEN_STOCK"(
    "AMOUNT" FLOAT(53) NOT NULL,
    "ARTICLE_NUMBER" INTEGER NOT NULL,
    "PRICE" FLOAT(53) NOT NULL,
    "PRICE_PER_UNIT" FLOAT(53) NOT NULL,
    "STOCK" FLOAT(53) NOT NULL,
    "STOCK_LIMIT" FLOAT(53),
    "STOCK_VALUE" FLOAT(53) NOT NULL,
    "CATEGORY_ID" BIGINT NOT NULL,
    "ID" BIGINT NOT NULL,
    "BRAND" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING(255),
    "SUPPLIER" CHARACTER VARYING(255),
    "TAX" CHARACTER VARYING(255),
    "UNIT" CHARACTER VARYING(255)
);     
ALTER TABLE "PUBLIC"."KITCHEN_STOCK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.KITCHEN_STOCK;           
CREATE CACHED TABLE "PUBLIC"."KITCHEN_CATEGORY"(
    "CATEGORY_ID" BIGINT NOT NULL,
    "CATEGORY_NAME" CHARACTER VARYING(255)
);          
ALTER TABLE "PUBLIC"."KITCHEN_CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("CATEGORY_ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.KITCHEN_CATEGORY;        
CREATE CACHED TABLE "PUBLIC"."MEAL_TIME"(
    "MEAL_TIME_ID" BIGINT NOT NULL,
    "MEAL_TIME_NAME" CHARACTER VARYING(255)
);               
ALTER TABLE "PUBLIC"."MEAL_TIME" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("MEAL_TIME_ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MEAL_TIME;               
CREATE CACHED TABLE "PUBLIC"."MENU_CATEGORY"(
    "MENU_CATEGORY_ID" BIGINT NOT NULL,
    "MENU_CATEGORY_NAME" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."MENU_CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_81" PRIMARY KEY("MENU_CATEGORY_ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MENU_CATEGORY;           
CREATE CACHED TABLE "PUBLIC"."MENU_ITEM"(
    "PRICE" FLOAT(53) NOT NULL,
    "MEAL_TIME_ID" BIGINT,
    "MENU_CATEGORY_ID" BIGINT,
    "MENU_ITEM_ID" BIGINT NOT NULL,
    "SUB_CATEGORY_ID" BIGINT,
    "DESCRIPTION" CHARACTER VARYING(255),
    "IMAGE" CHARACTER VARYING(255),
    "ITEM_NAME" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."MENU_ITEM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("MENU_ITEM_ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MENU_ITEM;               
CREATE CACHED TABLE "PUBLIC"."MENU_ITEM_STOCK"(
    "AMOUNT" FLOAT(53) NOT NULL,
    "ID" BIGINT NOT NULL,
    "KITCHEN_STOCK_ID" BIGINT,
    "MENU_ID" BIGINT
);        
ALTER TABLE "PUBLIC"."MENU_ITEM_STOCK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_41" PRIMARY KEY("ID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MENU_ITEM_STOCK;         
CREATE CACHED TABLE "PUBLIC"."ORDER_ITEM"(
    "PRICE" FLOAT(53) NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "MENU_ITEM_ID" BIGINT NOT NULL,
    "ORDER_ID" BIGINT NOT NULL,
    "ORDER_ITEM_ID" BIGINT NOT NULL
);  
ALTER TABLE "PUBLIC"."ORDER_ITEM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4B" PRIMARY KEY("ORDER_ITEM_ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_ITEM;              
CREATE CACHED TABLE "PUBLIC"."RESERVATION"(
    "GUEST" BOOLEAN NOT NULL,
    "NUMBER_OF_GUESTS" INTEGER NOT NULL,
    "ROOM_NUMBER" CHARACTER VARYING(6),
    "RESERVATION_ID" BIGINT NOT NULL,
    "CUSTOMER_PHONE" CHARACTER VARYING(20) NOT NULL,
    "CUSTOMER_EMAIL" CHARACTER VARYING(50) NOT NULL,
    "CUSTOMER_FIRST_NAME" CHARACTER VARYING(50) NOT NULL,
    "CUSTOMER_LAST_NAME" CHARACTER VARYING(50) NOT NULL,
    "RESERVATION_DATE" CHARACTER VARYING(255) NOT NULL,
    "RESERVATION_STATUS" CHARACTER VARYING(255) NOT NULL,
    "RESERVATION_TIME" CHARACTER VARYING(255) NOT NULL
);         
ALTER TABLE "PUBLIC"."RESERVATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_23" PRIMARY KEY("RESERVATION_ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESERVATION;             
CREATE CACHED TABLE "PUBLIC"."RESERVED_TABLE"(
    "RESERVATION_ID" BIGINT NOT NULL,
    "TABLE_ID" BIGINT NOT NULL
);     
ALTER TABLE "PUBLIC"."RESERVED_TABLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4C" PRIMARY KEY("RESERVATION_ID", "TABLE_ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESERVED_TABLE;          
CREATE CACHED TABLE "PUBLIC"."RESTAURANT_TABLES"(
    "TABLE_CAPACITY" INTEGER,
    "TABLE_NUMBER" INTEGER,
    "TABLE_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);              
ALTER TABLE "PUBLIC"."RESTAURANT_TABLES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2E" PRIMARY KEY("TABLE_ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESTAURANT_TABLES;       
CREATE CACHED TABLE "PUBLIC"."SUB_CATEGORY"(
    "SUB_CATEGORY_ID" BIGINT NOT NULL,
    "SUB_CATEGORY_NAME" CHARACTER VARYING(255)
);      
ALTER TABLE "PUBLIC"."SUB_CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_20" PRIMARY KEY("SUB_CATEGORY_ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SUB_CATEGORY;            
CREATE CACHED TABLE "PUBLIC"."USER_ROLE"(
    "ROLE_ID" BIGINT NOT NULL,
    "ROLE" CHARACTER VARYING(255)
);              
ALTER TABLE "PUBLIC"."USER_ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ROLE_ID");               
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.USER_ROLE;               
INSERT INTO "PUBLIC"."USER_ROLE" VALUES
(1, 'Admin'),
(2, 'Chef'),
(3, 'Front desk'),
(4, 'Waiter');      
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ROLE_ID" BIGINT,
    "USER_ID" BIGINT NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "FIRST_NAME" CHARACTER VARYING(255),
    "LAST_NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255)
);       
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" PRIMARY KEY("USER_ID");  
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
(1, 1, 'sabuidres@gmail.com', 'samir', 'abuidries', 'Samir@123', 'sabuidries');          
ALTER TABLE "PUBLIC"."ORDER_ITEM" ADD CONSTRAINT "PUBLIC"."FKGV4BNMO7CBIB2NH0B2RW9YVIR" FOREIGN KEY("ORDER_ID") REFERENCES "PUBLIC"."CUSTOMER_ORDER"("ORDER_ID") NOCHECK;     
ALTER TABLE "PUBLIC"."MENU_ITEM" ADD CONSTRAINT "PUBLIC"."FKG3I1QN1OPY3VKA1HG8UYQV4NV" FOREIGN KEY("SUB_CATEGORY_ID") REFERENCES "PUBLIC"."SUB_CATEGORY"("SUB_CATEGORY_ID") NOCHECK;          
ALTER TABLE "PUBLIC"."MENU_ITEM" ADD CONSTRAINT "PUBLIC"."FK7UPPL3OIG60OSIVAWT8PML1BU" FOREIGN KEY("MENU_CATEGORY_ID") REFERENCES "PUBLIC"."MENU_CATEGORY"("MENU_CATEGORY_ID") NOCHECK;       
ALTER TABLE "PUBLIC"."MENU_ITEM" ADD CONSTRAINT "PUBLIC"."FKETE942SDHGQ9QJWP9DP23DNQV" FOREIGN KEY("MEAL_TIME_ID") REFERENCES "PUBLIC"."MEAL_TIME"("MEAL_TIME_ID") NOCHECK;   
ALTER TABLE "PUBLIC"."RESERVED_TABLE" ADD CONSTRAINT "PUBLIC"."FK5EQ441W7V4LLD1908DGLPNHFV" FOREIGN KEY("RESERVATION_ID") REFERENCES "PUBLIC"."RESTAURANT_TABLES"("TABLE_ID") NOCHECK;        
ALTER TABLE "PUBLIC"."MENU_ITEM_STOCK" ADD CONSTRAINT "PUBLIC"."FK1PH20A6VLE28HWDHCCJXM5VI5" FOREIGN KEY("KITCHEN_STOCK_ID") REFERENCES "PUBLIC"."KITCHEN_STOCK"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."FKQJP6IWE2ANTHE5YX88FL0COAN" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."USER_ROLE"("ROLE_ID") NOCHECK; 
ALTER TABLE "PUBLIC"."MENU_ITEM_STOCK" ADD CONSTRAINT "PUBLIC"."FKKL42VFSOK4TV1XHKEQUA8K4RM" FOREIGN KEY("MENU_ID") REFERENCES "PUBLIC"."MENU_ITEM"("MENU_ITEM_ID") NOCHECK;  
ALTER TABLE "PUBLIC"."ORDER_ITEM" ADD CONSTRAINT "PUBLIC"."FK1MY78ITKET7MHYN3WT4G6J4SQ" FOREIGN KEY("MENU_ITEM_ID") REFERENCES "PUBLIC"."MENU_ITEM"("MENU_ITEM_ID") NOCHECK;  
ALTER TABLE "PUBLIC"."CUSTOMER_ORDER" ADD CONSTRAINT "PUBLIC"."FKM0YJJK0GI3JGRR9IVCUYXT6AM" FOREIGN KEY("RESERVATION_ID") REFERENCES "PUBLIC"."RESERVATION"("RESERVATION_ID") NOCHECK;        
ALTER TABLE "PUBLIC"."KITCHEN_STOCK" ADD CONSTRAINT "PUBLIC"."FKE34BXUYAT48NFVTO9G84S3BVV" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."KITCHEN_CATEGORY"("CATEGORY_ID") NOCHECK;          
ALTER TABLE "PUBLIC"."RESERVED_TABLE" ADD CONSTRAINT "PUBLIC"."FKIJTGNOG5FLG97G1O2TN1LBR12" FOREIGN KEY("TABLE_ID") REFERENCES "PUBLIC"."RESERVATION"("RESERVATION_ID") NOCHECK;              
